---
- hosts: all
  gather_facts: no
  tasks:
    - name: create file
      file:
        path: /tmp/file1
        state: touch
      register: output
    - debug: msg="register variable value {{ output }}"
    - name: edit file
      lineinfile:
        path: /tmp/file1
        line: "{{ansible_hostname}}-{{output.uid}}"