---

- name: regtest
  hosts: all
  connection: local

  vars:
    provider:
      password: admin
      server: localhost
      user: admin
      validate_certs: no
      server_port: 10443

  tasks:
    - name: Create file
      file:
        path: /tmp/file1
        state: touch
      register: output
    - debug: msg="register variable value {{ output }}"
    - name: edit file
      lineinfile:
        path: /tmp/file1
        line: "{{ansible_hostname}}-{{output.uid}}"